# Generated by Django 4.2.23 on 2025-07-20 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='followup_treatment',
            field=models.TextField(blank=True, help_text='Notes for the followup treatment session', null=True),
        ),
    ]
