# Generated by Django 4.2.23 on 2025-07-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_date_time_client_followup_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='followup_treatment',
        ),
    ]
