# Generated by Django 4.2.23 on 2025-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_followup_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
    ]
